### ISSUE TITLE
Kan inte unsetta något

### ISSUE THREAD

**Issue by Bjorn-Andersson** [Kekos/query-builder#1]
![image](https://github.com/Kekos/query-builder/assets/97664991/0835b697-c324-4a88-ba2f-97225ba05030)

Nått sånt här kanske hade vart najs?

**Comment by Kekos** [comment]
You are welcome to make a PR with such feature!

**Comment by Kekos** [comment]
You can use `setColumns()` or `setJoins()` to clear those.
